name: liqpay
description: LiqPay payment service wrapper library to be used on a client or server side dart.
version: 0.0.1+1
homepage: https://github.com/Newgarden-Solutions/liqpay

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Network
  http: ^1.0.0
  http_interceptor: ^2.0.0-beta.7

  # Utility
  uuid: ^3.0.7
  equatable: ^2.0.5

  # Security
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  mockito: ^5.4.2
